{% set name = "bw2parameters" %}
{% set version = "0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/bw2parameters-{{ version }}.tar.gz
  sha256: f9d6cd45488762a755ede5c11754d5acf790f1e8ab592a86babd02f91c08a87a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - asteval
    - astunparse
    - numpy
    - python >=3.6
    - stats_arrays

test:
  imports:
    - bw2parameters
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/brightway-lca/brightway2-parameters
  license: BSD-3-Clause
  license_family: BSD
  license_file:
    - LICENSE
  summary: Library for storing, validating, and calculating with parameters. Designed to work with the Brightway2 life cycle assessment framework, but is generic enough to work in other use cases.
  dev_url: https://github.com/brightway-lca/brightway2-parameters

extra:
  recipe-maintainers:
    - cmutel
    - xylar
